### PR TITLE
GUI/event handling/58

### PR DESCRIPTION
**Pull request by osvegn**
This pull request is link to the issue #58.
It creates the Event class to handle SFML event easier.

### CODE REVIEW

**Review by GuyomT — APPROVED** [review]
LGTM !

**Review by LucasTesnier — APPROVED** [review]
The use of static inline il C++ are not prohibed ? I repember that the only way to write some code in a .hpp is with template

**Review by Cavonstavant — APPROVED** [review]
Good use of inline functions, nothing to report

**Comment by osvegn** [comment]
> The use of static inline il C++ are not prohibed ? I repember that the only way to write some code in a .hpp is with template

Be careful, it's not `static inline` but `inline` functions. It's allow if you write code in 2-3 lines. It's allow when you just return a value or if you set a private variable in a class.

**Pull request merged**
